---
database_file: "/home/philipf/Dropbox/timetrap/.timetrap.db"
round_in_seconds: 900
append_notes_delimiter: " "
formatter_search_paths:
- "/home/philipf/.timetrap/formatters"
default_formatter: text
auto_sheet: dotfiles
auto_sheet_search_paths:
- "/home/philipf/.timetrap/auto_sheets"
default_command: 
auto_checkout: true
require_note: false
note_editor: vim
week_start: Monday
day_length_hours: 8
progress_width: 40
day_exclude_sheets:
- lunch
day_countdown: true
sheets_are_exclusive: true
